# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OlQ-fQWjbbdlJVD_sLqY6xspbiz7HmIW
"""

# Python course for beginners
data = {
"number":[1 ,2 ,3 ,4 ,5 ,6],
"gender":[ "female", "female", "female", "female", "male", "female"],
"age": [22 ,45 ,33 ,23 ,33 ,21],
"depression": [0 ,0 ,0 ,0 ,1 ,1]
import pandas as pd
# Week 1
# assignment by Gal Alon 212537831
}
df1 = pd.DataFrame(data)
df1.to_csv("my_data.csv")